### ISSUE TITLE
Can you add .less type file recognition? Thank you

### ISSUE THREAD

**Issue by LBC100** [Youzhigang/react-app-rewire-less-with-modules#2]
Can you add .less type file recognition? Thank you。

**Comment by ethanyou725** [comment]
@LBC100, uh... Exactly I didn't understood what u mean, more details, thanks!😊 Welcome PR.

**Comment by LBC100** [comment]
css modules only support for *.module.css or *.module.less。Please let the program recognize the .less file 。Demo: // src/App.js

import React from 'react';
import styles from './App.less';

export default ({text}) => (
    <div className={styles.app}>{text}</div>
)。Finally, thank you very much

**Comment by ethanyou725** [comment]
you can  rename `App.less` to  `App.module.less`, it will work well.
as you do, we can't write normal css or less, only css modules

**Comment by LBC100** [comment]
.module.less. The byte is too long. The experience is terrible, request to join ".less". Demo: import styles from './App.less'. Thank you

**Comment by LBC100** [comment]
const path = require('path');
const {injectBabelPlugin} = require('react-app-rewired');

module.exports = function override(config, env) {
    config = less_modules(config);
    return config;
}




const less_modules_obj = {
    test: /\.less$/,
    exclude: /node_modules/,
    use: [
      require.resolve('style-loader'),
      {
        loader: require.resolve('css-loader'),
        options: {
          modules: true,
          importLoaders: 1,
          localIdentName: '[name]__[local]__[hash:base64:5]',
        },
      },
      {
        loader: require.resolve('postcss-loader'),
        options: {
          // Necessary for external CSS imports to work
          // https://github.com/facebookincubator/create-react-app/issues/2677
          ident: 'postcss',
          plugins: () => [
            require('postcss-flexbugs-fixes'),
            autoprefixer({
              browsers: [
                '>1%',
                'last 4 versions',
                'Firefox ESR',
                'not ie < 9', // React doesn't support IE8 anyway
              ],
              flexbox: 'no-2009',
            }),
          ],
        },
      },
      {
        loader: require.resolve('less-loader') // compiles Less to CSS
      }
    ],
  } 

function less_modules (config) {
    //过滤出包含oneOf的数组
    const oneOfRule = config.module.rules.find(
        rule => rule.oneOf !== undefined,
    );
    //在oneOf添加一个新的规则
    oneOfRule.oneOf.unshift(less_modules_obj);
    return config
}

**Comment by ethanyou725** [comment]
rule is rule, only support for *.module.css or *.module.less
