### ISSUE TITLE
option javascriptEnabled not working properly

### ISSUE THREAD

**Issue by victorlev01** [Youzhigang/react-app-rewire-less-with-modules#3]
I'm using less-loader with ant design, and its less styles require to have "javascriptEnabled" option.
Tried using your plugin with option 
`module.exports = function override(config, env) {
    config = rewireLessModules(config, env, {
        javascriptEnabled: true
    });`
but encountered error
`// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in C:\programs\IdeaProjects\front\node_modules\antd\lib\style\color\bezierEasing.less (line 110, column 0)`

i havent found working solution for a problem aside from roadhog-js, but i'm using react-app rewired so i made a workaround:
` config = rewireLessModules(config, env, {
        javascriptEnabled: true
    });

    const rules = config.module.rules.filter(function (rule) {
        return rule.oneOf !== undefined;
    });
    rules.forEach(function (rule) {
        rule.oneOf && rule.oneOf.forEach(function (singleRule) {
            singleRule.use && singleRule.use.forEach(function (loader) {
                if (typeof loader === 'string') {
                    console.log(loader);
                    const loaderIndex = singleRule.use.indexOf(loader);
                    const loaderWithOptions = {
                        "loader": loader,
                        "options": {
                            "javascriptEnabled": "true",
                            "modules": true,
                            "localIdentName": "[local]___[hash:base64:5]",
                            "importLoaders": 1
                        }
                    };
                    singleRule.use[loaderIndex] = loaderWithOptions;
                }
            })
        })
    });`

problem is - react-app-rewire-less-with-modules ignores **javascriptEnabled** option
can you look into this? thanks in advance

**Comment by ethanyou725** [comment]
make sure the devDependencies
```
"less": "^2.7.3",
 "less-loader": "^4.0.5",
```
less version can't upgrade to 3.x

**Comment by victorlev01** [comment]
thanks for advice.
on less 2.7.3  its working without workarounds.
i previously used
`"less": "^3.0.2",
    "less-loader": "^4.1.0"`
